EMOJIS_LOVE = {
  '1f493' => { code: "\u{1f493}", alt: '💓', title: 'Beating Heart' },
  '1f5a4' => { code: "\u{1f5a4}", alt: '🖤', title: 'Black Heart' },
  '2665'  => { code: "\u{2665}",  alt: ' ', title: ' Heart Suit' },
  '1f499' => { code: "\u{1f499}", alt: '💙', title: 'Blue Heart' },
  '1f491' => { code: "\u{1f491}", alt: '💑', title: 'Couple with Heart' },
  '1f618' => { code: "\u{1f618}", alt: '😘', title: 'Face Blowing a Kiss' },
  '1f49a' => { code: "\u{1f49a}", alt: '💚', title: 'Green Heart' },
  '1f497' => { code: "\u{1f497}", alt: '💗', title: 'Growing Heart' },
  '1f49f' => { code: "\u{1f49f}", alt: '💟', title: 'Heart Decoration' },
  '1f498' => { code: "\u{1f498}", alt: '💘', title: 'Heart with Arrow' },
  '1f49d' => { code: "\u{1f49d}", alt: '💝', title: 'Heart with Ribbon' },
  '2763'  => { code: "\u{2763}",  alt: ' ', title: ' Heart Exclamation' },
  '1f617' => { code: "\u{1f617}", alt: '😗', title: 'Kissing Face' },
  '1f61a' => { code: "\u{1f61a}", alt: '😚', title: 'Kissing Face with Closed Eyes' },
  '1f3e9' => { code: "\u{1f3e9}", alt: '🏩', title: 'Love Hotel' },
  '1f48c' => { code: "\u{1f48c}", alt: '💌', title: 'Love Letter' },
  '1f9e1' => { code: "\u{1f9e1}", alt: '🧡', title: 'Orange Heart' },
  '1f49c' => { code: "\u{1f49c}", alt: '💜', title: 'Purple Heart' },
  '1f49e' => { code: "\u{1f49e}", alt: '💞', title: 'Revolving Hearts' },
  '1f380' => { code: "\u{1f380}", alt: '🎀', title: 'Ribbon' },
  '1f339' => { code: "\u{1f339}", alt: '🌹', title: 'Rose' },
  '1f63b' => { code: "\u{1f63b}", alt: '😻', title: 'Smiling Cat with Heart-Eyes' },
  '1f60d' => { code: "\u{1f60d}", alt: '😍', title: 'Smiling Face with Heart-Eyes' },
  '1f970' => { code: "\u{1f970}", alt: '🥰', title: 'Smiling Face with Hearts' },
  '1f496' => { code: "\u{1f496}", alt: '💖', title: 'Sparkling Heart' },
  '1f9a2' => { code: "\u{1f9a2}", alt: '🦢', title: 'Swan' },
  '1f495' => { code: "\u{1f495}", alt: '💕', title: 'Two Hearts' },
  '1f90d' => { code: "\u{1f90d}", alt: '🤍',  title: 'White Heart' },
  '1f381' => { code: "\u{1f381}", alt: '🎁', title: 'Wrapped Gift' },
  '1f49b' => { code: "\u{1f49b}", alt: '💛', title: 'Yellow Heart' }
}

# TODO: add ❤️
# FE0F
